### ISSUE TITLE
Hera dev instructions can't use PyPI

### ISSUE THREAD

**Issue by zmoon** [NOAA-CSL/MELODIES-MONET#79]
The current recommended dev install method [^1]
```
pip install --no-deps --editable .
```
doesn't work[^2] because the build process tries to download a fresh setuptools from PyPI, but Hera doesn't allow downloading from there.

An alternative (which has been tested to work) is
```
python setup.py develop --no-deps
```

[^1]: Currently recommended for monet/monetio
[^2]: This was reported by Megan Bela.

**Comment by zmoon** [comment]
Although this is another issue, I think at this point we can recommend using monet/monetio from conda-forge, *unless* you are planning to modify something in those packages.

**Comment by zmoon** [comment]
I'm going to wait to address this until #80 with the updated setup config is merged.

**Comment by rschwant** [comment]
@zmoon I agree we should update the MELODIES-MONET readthedocs page to just point to the monet and monetio conda-forge repositories for now since you are planning to just keep these up to date. 

Related to this, it appears that Hera now does not have problems downloading multiple packages at a time anymore, so we could just recommend the following, which I tested works well:

conda create --name melodies-monet python=3.9
conda activate melodies-monet
conda install -y -c conda-forge netcdf4 wrf-python jupyterlab monet monetio

Then I recommend we just suggest in these basic instructions to just download MELODIES-MONET via html to make it as simple as possible. 
git clone https://github.com/NOAA-CSL/MELODIES-MONET.git

Then we can move the current installation instructions as part of the developer's guide instead, so that developers know how to link these different branches to their conda environment, but average users do not have to worry about this. For the aircraft evaluation development that we are working on at NOAA CSL we need to point to this branch on MONET. 
https://github.com/NOAA-OAR-ARL/monet/tree/dev-combine_to_da

Within the current framework, how would we do this on Hera? 

What do you think of this plan? I think this is consistent mostly with what we discussed last meeting.

**Comment by zmoon** [comment]
To use a different monet/monetio from GitHub (after following your initial steps above), in principle you can use this method that we use in the CI to grab the `develop` branch versions:

https://github.com/NOAA-CSL/MELODIES-MONET/blob/0727db674d1fd41748fca2a9d7255f40fff07d87/.github/workflows/ci.yml#L40-L41

However, currently on Hera that would have the same problem as this issue.

If you are going to be potentially modifying it anyway (like in your aircraft example), you would
1. clone the repo
2. check out your branch
3. editable install using  
   ```
   python setup.py develop --no-deps
   ```
   as above

I'm going to try to come up with a bit of Bash that a Hera user could use to get a certain GitHub branch without intention of editing.

**Comment by zmoon** [comment]
Hmm, I just tried installing some things on Hera from PyPI and had no issue. Maybe they changed the policy very recently? @rschwant @bbakernoaa ?

**Comment by rschwant** [comment]
I'm confused too because I tried both the old way and your new way today and both work fine. Is one method preferred over the other?

**Comment by bbakernoaa** [comment]
They must have just changed it :). I tried last week when @meganbela had these issues and it didn’t work. 

Glad this issue seems to be resolved though.

**Comment by zmoon** [comment]
> I tried both the old way and your new way today and both work fine. Is one method preferred over the other?

`pip install` methods should be preferred over invoking `setup.py` directly. Some info [here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary) if interested.

**Comment by rschwant** [comment]
Great, well let's keep with the pip install for now. But now we have a backup in case Hera restrictions change again or if other computers have similar problems.

**Comment by zmoon** [comment]
I think this has been sufficiently resolved.
